### ISSUE TITLE
No dependency when install via pip

### ISSUE THREAD

**Issue by boltomli** [codesardine/Jade-Application-Kit#62]
##  BUGS

After a fresh `pip install -U Jade-Application-Kit` it won't work in Python console.

```
>>> from JAK.Application import JWebApp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python\current\lib\site-packages\JAK\Application.py", line 9, in <module>
    from PySide2.QtCore import Qt, QCoreApplication
ModuleNotFoundError: No module named 'PySide2'
```

#### Expected Behavior

The basic use of `import` should work.

#### Actual Behavior

The dependency is not available after fresh install.

#### Possible Fix

Manually install the dependency `pip install -U PySide2` then the issue is gone.

#### Steps to Reproduce

1. `virtualenv -p python3 venv`
1. `source venv/bin/activate`
1. `pip install -U Jade-Application-Kit`
1. `python`
1. `from JAK.Application import JWebApp`

#### Your Environment

Pygi version:
python version: 
Linux distro:
Link to your project:

**Comment by Steffan153** [comment]
I probably made a mistake when I edited the description. Try cloning this repository and running `pip install -r requirements.txt` (in the directory where you put the repo).

**Comment by boltomli** [comment]
Oh, it happens only when install from pip. It works well in the repo.

**Comment by codesardine** [comment]
I could add this on setup.py:
```
install_requires=[
          'PySide2',
      ],
```
The problem here is that setup.py does not have an argument to install without dependencies and will install from the distribution repositories and also pip repositories, as it can be seen in the package below:
https://gitlab.manjaro.org/packages/community/webdad/python-jade-application-kit/blob/master/PKGBUILD

That's why I have requirements.txt instead, can't see a workaround for this if you have one let me know.

>  File "C:\python\current\lib\site-packages\JAK\Application.py", line 9, in <module>

Also I don't support Windows, so I am not sure if JAK works for you, anyway let me know if it does.

**Comment by boltomli** [comment]
Thanks, I understand. I'll see if there's a way to support both pacman and pip. By the way it's the same behaviour in Linux. I didn't get it work on Windows yet but WSL with X server may work (basically a working Linux env)
